# Day 1 — NumPy Basics

- Arrays and dtypes
- Indexing and slicing
- Vectorisation
- Broadcasting
- Mini analytics example

## 1. Array Creation

In [39]:
import numpy as np

# Basic 1D array
a = np.array([1,2,3,4,5])
print("a:", a, "| shape:", a.shape, "| dtype:", a.dtype)

# 2D array
b = np.array([[1,2,3],[4,5,6]])
print("b:\n", b)
print("| shape:", b.shape, "| ndim:", b.ndim)

# Zeros, ones, arange, linspace
zeros = np.zeros((2,3))
ones = np.ones((3,2))
arange_arr = np.arange(0,10,2)
linspace_arr = np.linspace(0,1,5)

print("zeros:", zeros)
print("ones:", ones)
print("arange:", arange_arr)
print("linspace:", linspace_arr)

a: [1 2 3 4 5] | shape: (5,) | dtype: int64
b:
 [[1 2 3]
 [4 5 6]]
| shape: (2, 3) | ndim: 2
zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1.]
 [1. 1.]
 [1. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


In [40]:
# shapes and reshape:

c = np.arange(12)
print("c:", c, "shape:", c.shape)

c2 = c.reshape(3,4)
print("c reshaped to (3,4):", c2)

c3 = c.reshape(2,2,3)
print("c reshaped to (2,2,3)", c3)



c: [ 0  1  2  3  4  5  6  7  8  9 10 11] shape: (12,)
c reshaped to (3,4): [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
c reshaped to (2,2,3) [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


Summary = Array Creation: what arrays are and how shapes/dtypes matter.

## 2. Indexing and slicing

In [41]:
arr = np.array([10,20,30,40,50])
print("arr:", arr)

# Basic indexing
print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing
print("first three:", arr[:3])
print("Middle part (index 1 to 3):", arr[1:4])

# step slicing
print("every second element:", arr[::2])


arr: [10 20 30 40 50]
First element: 10
Last element: 50
first three: [10 20 30]
Middle part (index 1 to 3): [20 30 40]
every second element: [10 30 50]


In [42]:
# 2D Indexing
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("m:", m)

print("Element at row 0, col 1:", m[0, 1])
print("first row:", m[0, :])
print("second element:", m[:, 1])

#submatrix: top-left 2*2
print("top left 2*2:", m[:2, :2])


m: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, col 1: 2
first row: [1 2 3]
second element: [2 5 8]
top left 2*2: [[1 2]
 [4 5]]


In [43]:
# Boolean Indexing:

nums = np.array([3, 8, 12, 5, 7, 20])
print("nums:", nums)

mask = nums > 7
print("mask:", mask)

filtered = nums[mask]
print("nums > 7:", filtered)

# combine condition
mask2 = (nums > 5) & (nums < 15)
print("5 < nums < 15:", nums[mask2])

nums: [ 3  8 12  5  7 20]
mask: [False  True  True False False  True]
nums > 7: [ 8 12 20]
5 < nums < 15: [ 8 12  7]


Summary = Indexing/Slicing: how to access subsets and filter data

## 3. Vectorisation

In [44]:
x = np.array([1,2,3,4,5])
y = np.array([10,20,30,40,50])

print("x:", x)
print("y:", y)

print("x + y", x+y)
print("x - y", x-y)
print("x squared", x**2)
print("x + 10", x+10)


x: [1 2 3 4 5]
y: [10 20 30 40 50]
x + y [11 22 33 44 55]
x - y [ -9 -18 -27 -36 -45]
x squared [ 1  4  9 16 25]
x + 10 [11 12 13 14 15]


In [45]:
# reduction and dot

v = np.array([1,2,3,4,5])

print("sum:", np.sum(v))
print("mean:", np.mean(v))
print("max:", np.max(v), "argmax(index):", np.argmax(v))

#dot product
u = np.array([10,20,30,40,50])
print("u:", u)
print("dot(u,v):", np.dot(u,v))
print("using @ operator:", u@v)


sum: 15
mean: 3.0
max: 5 argmax(index): 4
u: [10 20 30 40 50]
dot(u,v): 550
using @ operator: 550


Summary = Vectorisation: operations on whole arrays instead of loops.

## 4. Broadcasting

In [46]:
M = np.array([[1,2,3],
              [4,5,6]])
print("M:", M, "shape:", M.shape)

row = np.array([10,20,30])
print("row:", row, "shape:", row.shape)

print("M + row", M+row)

M: [[1 2 3]
 [4 5 6]] shape: (2, 3)
row: [10 20 30] shape: (3,)
M + row [[11 22 33]
 [14 25 36]]


Summary = Broadcasting: auto-expanding shapes.

## 5. Mini analytics example

In [47]:
np.random.seed(42)

# Suppose we have 100 customers
n_customers = 100

# Random prices between 10 and 100
prices = np.random.uniform(10, 100, size=n_customers)

# Random quantities between 1 and 5
quantities = np.random.randint(1, 6, size=n_customers)

# Random discounts between 0% and 30%
discounts = np.random.uniform(0.0, 0.3, size=n_customers)

print("prices (first 5):", prices[:5])
print("quantities (first 5):", quantities[:5])
print("discounts (first 5):", discounts[:5])

prices (first 5): [43.7086107  95.56428758 75.87945476 63.87926358 24.04167764]
quantities (first 5): [1 4 5 4 5]
discounts (first 5): [0.22056484 0.06272149 0.16243439 0.20873532 0.06856501]


In [48]:
# Revenue without discounts
revenue = prices * quantities  # vectorised

# Revenue with discounts
revenue_after_discount = revenue * (1 - discounts)

print("Total revenue (no discount):", revenue.sum())
print("Total revenue (with discount):", revenue_after_discount.sum())
print("Average revenue per customer (with discount):", revenue_after_discount.mean())

Total revenue (no discount): 15812.731056563774
Total revenue (with discount): 13367.566345570225
Average revenue per customer (with discount): 133.67566345570225


In [49]:
# Customers with high discount (> 20%)
high_discount_mask = discounts > 0.2
high_discount_revenue = revenue_after_discount[high_discount_mask]

print("Number of high-discount customers:", high_discount_mask.sum())
print("Avg revenue for high-discount customers:", high_discount_revenue.mean())


Number of high-discount customers: 34
Avg revenue for high-discount customers: 113.32818974601551


Summary
- Used vectorised operations to compute revenue for 100 customers.
- Applied discounts using broadcasting.
- Used boolean masks to focus on a subset (high-discount customers).